version: '3.7'
services:
    fieldsets-local:
        build:
            context: ./
            dockerfile: ${FIELDSETS_LOCAL_CONFIG_PATH:-./config/local/}Dockerfile
            args:
                TIMEZONE: ${TIMEZONE:-America/New_York}
                POSTGRES_VERSION: ${POSTGRES_VERSION:-15}
                POSTGRES_PORT: ${POSTGRES_PORT:-5432}
        container_name: fieldsets-local
        hostname: fieldsets-local
        tty: ${ENABLE_TERMINAL:-true}
        networks:
            default:
                ipv4_address: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}

networks:
    default:
        driver: bridge
        name: fieldsets_network
        attachable: true
        ipam:
            config:
            - subnet: ${FIELDSETS_LOCAL_NETWORK_SUBNET:-172.28.0.0/24}

    