volumes:
    fieldsets-plugins:
        driver: local
        name: fieldsets-plugins
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './plugins'
    fieldsets-apps:
        driver: local
        name: fieldsets-apps
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './src'
    fieldsets-lib:
        driver: local
        name: fieldsets-lib
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './lib'
    fieldsets-data:
        driver: local
        name: fieldsets-data
        driver_opts:
          type: 'none'
          o: 'bind'
          device: './data'

include:
  - path: ${FIELDSETS_CONFIG_PATH:-./config/}docker/docker-compose.volumes.yml
    project_directory: ${FIELDSETS_PATH:-./}
    env_file: ${FIELDSETS_PATH:-./}.env
  - path: ${FIELDSETS_PLUGINS_PATH:-./plugins/}docker-compose.volumes.yml
    project_directory: ${FIELDSETS_PATH:-./}
    env_file: ${FIELDSETS_PATH:-./}.env