x-envvars-db: &envvars-db
  FIELDSETS_DB: ${FIELDSETS_DB:-postgres}
  FIELDSETS_DB_HOST: ${FIELDSETS_DB_HOST:-${POSTGRES_HOST:-172.28.0.7}}
  FIELDSETS_DB_PORT: ${FIELDSETS_DB_PORT:-${POSTGRES_PORT:-5423}}
  FIELDSETS_DB_VERSION: ${FIELDSETS_DB_VERSION:-${POSTGRES_VERSION:-15}}
  FIELDSETS_DB_USER: ${FIELDSETS_DB_USER:-${POSTGRES_USER:-fieldsets}}
  FIELDSETS_DB_PASSWORD: ${FIELDSETS_DB_PASSWORD:-${POSTGRES_PASSWORD:-fieldsets}}
  FIELDSETS_DB_NAME: ${FIELDSETS_DB_NAME:-${POSTGRES_DB:-fieldsets}}
  FIELDSETS_DB_SCHEMA: ${FIELDSETS_DB_SCHEMA:-${POSTGRES_SCHEMA:-fieldsets}}