x-envvars-cache: &envvars-cache
  FIELDSETS_CACHE: ${FIELDSETS_CACHE:-memcached}
  FIELDSETS_CACHE_NAME: ${FIELDSETS_CACHE_NAME:-"fieldsets-cache"}
  FIELDSETS_CACHE_HOST: ${FIELDSETS_CACHE_HOST:-${FIELDSETS_LOCAL_HOST:-:-172.28.0.6}}
  FIELDSETS_CACHE_PORT: ${FIELDSETS_CACHE_PORT:-11211}