x-envvars-logger: &envvars-logger
  FIELDSETS_LOGGER: ${FIELDSETS_LOGGER:-fluentbit}}
  FIELDSETS_LOGGER_HOST: ${FIELDSETS_LOGGER_HOST:-172.28.0.2}}
  FIELDSETS_LOGGER_PORT: ${FIELDSETS_LOGGER_PORT:-24224}}