networks:
    default:
        driver: bridge
        attachable: true
        ipam:
            config:
            - subnet: ${FIELDSETS_NETWORK_SUBNET:-172.28.0.0/24}

services:
    fieldsets-logger:
      networks:
        default:
          ipv4_address: ${LOGGER_HOST:-172.28.0.2}

    fieldsets-db:
      environment:
        FIELDSETS_LOCAL_HOST: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
      networks:
        default:
          ipv4_address: ${POSTGRES_HOST:-172.28.0.7}
      logging:
        driver: fluentd
        options:
          fluentd-address: ${LOGGER_HOST:-172.28.0.2}:${LOGGER_PORT:-24224}
          tag: debug_log.postgres
          fluentd-async: "true"
          env: "PGOPTIONS='-c search_path=pipeline',ENABLE_LOGGING='${ENABLE_LOGGING:-false}'"

    fieldsets-local:
      volumes:
        - ${FIELDSETS_CONFIG_PATH:-./config/}local/.bashrc:/root/.bashrc
        - ${FIELDSETS_CONFIG_PATH:-./config/}local/.bash_profile:/root/.profile
        - ./.env:/root/.env
      networks:
        default:
          ipv4_address: ${FIELDSETS_LOCAL_HOST:-172.28.0.6}
      logging:
        driver: fluentd
        options:
          fluentd-address: ${LOGGER_HOST:-172.28.0.2}:${LOGGER_PORT:-24224}
          tag: debug_log.local
          fluentd-async: "true"
          env: "PGOPTIONS='-c search_path=pipeline',ENABLE_LOGGING='${ENABLE_LOGGING:-false}'"

    fieldsets-store:
      networks:
        default:
          ipv4_address: ${CLICKHOUSE_HOST:-172.28.0.5}
      logging:
        driver: fluentd
        options:
          fluentd-address: ${LOGGER_HOST:-172.28.0.2}:${LOGGER_PORT:-24224}
          tag: debug_log.clickhouse
          fluentd-async: "true"
          env: "PGOPTIONS='-c search_path=pipeline',ENABLE_LOGGING='${ENABLE_LOGGING:-false}'"

